package com.artisanat_backend.enums;

public enum Specialty {
    WEAVING, EMBROIDERY, CARPET_MAKING, LEATHERWORK, SHOE_MAKING, WOOD_CARVING,
    FURNITURE_MAKING, MARQUETRY, JEWELRY_MAKING, METALWORK, POTTERY,
    STONEMASONRY, GLASSBLOWING, TAPESTRY, MOSAIC_MAKING
}
