spring:
  application:
    name: artisanat-backend
  datasource:
    url: jdbc:mysql://localhost:3306/artisanat_maroc_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  sql:
    init:
      platform: mysql
  profiles:
    active: docker
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: chaimaalachhab555@gmail.com
    password: haxo irvw papo hkue
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    expiration-time: 3600000
server:
  port: 8080