/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-jewelry-shop",
  templateUrl: "./jewelry-shop.component.html",
  styleUrls: ["./jewelry-shop.component.css"],
  standalone: true
})
export class JewelryShopComponent {
  // Component logic goes here
}
